# Generated by Django 5.1.3 on 2024-12-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ввод пользователя')),
            ],
            options={
                'verbose_name': 'Ввод пользователя',
                'verbose_name_plural': 'Ввод пользователей',
            },
        ),
    ]
