# Generated by Django 5.1.3 on 2024-12-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='UserInput',
            options={'verbose_name': 'Ввод пользователя', 'verbose_name_plural': 'Ввод пользователей'},
        ),
    ]
